apiVersion: v1
kind: ConfigMap
metadata:
  name: arconia-config
  namespace: arconia
  labels:
    app.kubernetes.io/name: spring-boot-arconia
    app.kubernetes.io/component: config
data:
  SPRING_PROFILES_ACTIVE: "kubernetes"
  SERVER_PORT: "8080"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "*"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "always"
---
apiVersion: v1
kind: Secret
metadata:
  name: arconia-secrets
  namespace: arconia
  labels:
    app.kubernetes.io/name: spring-boot-arconia
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgresql:5432/arconia_db"
  SPRING_DATASOURCE_USERNAME: "arconia"
  SPRING_DATASOURCE_PASSWORD: "arconia"
  SPRING_DATA_REDIS_HOST: "redis"
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
